plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '8.3.5'
}

group = 'be.michielve'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    
    // Flyway dependencies (Core + Postgres support)
    implementation 'org.flywaydb:flyway-core:11.2.0'
    implementation 'org.flywaydb:flyway-database-postgresql:11.2.0'
    
    implementation 'io.hypersistence:hypersistence-utils-hibernate-63:3.9.0'
    implementation 'org.postgresql:postgresql:42.7.5' 

    implementation 'com.amazonaws:aws-lambda-java-core:1.2.3'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.3'
    implementation 'com.amazonaws.serverless:aws-serverless-java-container-springboot3:2.1.5'
    implementation platform('software.amazon.awssdk:bom:2.30.13')
    implementation 'software.amazon.awssdk:secretsmanager'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    implementation 'org.jsoup:jsoup:1.22.1'
    implementation 'org.json:json:20240303'
    implementation 'org.apache.commons:commons-lang3:3.18.0'
    implementation 'io.github.cdimascio:dotenv-java:3.1.0'

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.wiremock:wiremock-jetty12:3.13.2'
}

springBoot {
    mainClass = 'be.michielve.f1_api.F1ApiApplication'
}

shadowJar {
    archiveFileName = 'f1_api.jar'
    mergeServiceFiles()
    append 'META-INF/spring.handlers'
    append 'META-INF/spring.schemas'
    append 'META-INF/spring.tooling'
    append 'META-INF/spring.factories'
    append 'META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports'
    append 'META-INF/spring/org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration.imports'
    append 'META-INF/services/java.sql.Driver'
}

tasks.named('test') {
    systemProperty "wiremock.record", System.getProperty("wiremock.record")
    useJUnitPlatform()
}

dependencyLocking {
    lockAllConfigurations()
}